### ISSUE TITLE
[Widget Switch] Toggle mode doesn't work anymore

### ISSUE THREAD

**Issue by sgallou** [Yadoms/yadoms#410]
On 2_0_0 branch : toggle mode doesn't work anymore, with this log in console :

Uncaught ReferenceError: toggleCommand is not defined
    at switchViewModel.change (eval at parseBindingsString (http://192.168.0.19:8080/libs/knockout/js/knockout-3.4.0.js:68:90), <anonymous>:3:201)
    at HTMLInputElement.<anonymous> (http://192.168.0.19:8080/libs/knockout/js/knockout-3.4.0.js:89:443)
    at HTMLInputElement.dispatch (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:3:7537)
    at HTMLInputElement.r.handle (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:3:5620)
    at Object.trigger (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:4:4818)
    at HTMLInputElement.<anonymous> (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:4:5328)
    at Function.each (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:2:2861)
    at n.fn.init.each (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:2:845)
    at n.fn.init.trigger (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:4:5304)
    at n.fn.init.n.fn.(anonymous function) [as change] (http://192.168.0.19:8080/libs/jquery/js/jquery-2.2.4.min.js:4:5744)

**Comment by jmberhault** [comment]
closed in branch 2_0_0
